export { default as HomeLayout } from "./HomeLayout"
export { default as Checkout } from "./Checkout"
export { default as Landing } from "./Landing"
export { default as Login } from "./Login"
export { default as SingleProduct } from "./SingleProduct"
export { default as Register } from "./Register"
export { default as Error } from "./Error"
export { default as Category } from "./Category"